### ISSUE TITLE
ReadTheDocs: Basic Demo link broken

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/chippr#45]
Following #44 perhaps? 
```
Error: Cannot load file https://raw.githubusercontent.com/aimalz/chippr/docs/notebooks/demo2.ipynb
```

**Comment by aimalz** [comment]
Whoops, I had a bad link in the `index.rst` file, due to careless copy-pasting from [`qp`](https://github.com/aimalz/qp) when I started this repository.  It's fixed now, and the link in the `README` has been updated.  Thanks for catching this!

**Comment by drphilmarshall** [comment]
I see it now! Very nice. One small comment: in general, but for tutorials in particular, it's good to preserve the namespace of the package, so that it's clear where functions are coming from. This would mean removing the line `from chipper import *` and then adding an explicit `chipper.` in front of every `chippr` object. Without this it's much harder to see how much value `chippr` is adding. Just a thought!

**Comment by aimalz** [comment]
Good point, thanks!  The suggested change should now be reflected in the links.  (-:
