### ISSUE TITLE
Propagate n(z) estimates to cosmology

### ISSUE THREAD

**Issue by aimalz** [aimalz/chippr#49]
I had this implemented in the [previous version](https://github.com/aimalz/prob-z/tree/master/nz) using [randomfield](https://github.com/dkirkby/randomfield) and will re-implement it.

**Comment by aimalz** [comment]
There is now a plan for how to close this issue:
1. Via #60, scale up the number of galaxies `chippr` can handle to ~1 million.
2. Obtain data vectors (2PCFs) and BPZ p(z)s (and their interim prior) for Buzzard from @j-dr.
3. Use [cosmosis](https://bitbucket.org/joezuntz/cosmosis/wiki/Home) to obtain likelihoods in the space of cosmological parameters given combinations of the fixed data vectors and n(z) derived from the BPZ p(z)s under different estimation methods.

**Comment by drphilmarshall** [comment]
You should make this an _epic_ - I can imagine multiple issues belonging to
this over-arching one. Good to have a plan! :-)

>

**Comment by j-dr** [comment]
Just flagging that the DES-like catalogs that I'll be giving you are actually closer to 10M galaxies, not 1M.

**Comment by drphilmarshall** [comment]
Yes! Although in each tomographic source plane bin I heard that there will
be ~2 million source plane galaxies (and more like 200k galaxies in each
lens plane bin).

**Comment by j-dr** [comment]
Ah, right, so I guess the 2 million number is the important one.

**Comment by aimalz** [comment]
Update: The plan is to do this with [cosmosis](https://bitbucket.org/joezuntz/cosmosis).

**Comment by aimalz** [comment]
This is actually in decent shape now.  (See plot [here](https://github.com/aimalz/chippr/blob/master/research/paper/fig/final_plot.png), don't mind the obvious sign error in one panel.)  Thanks @elikrause!!!  I'm not sure I'm interpreting this quite right yet, but progress is definitely being made.

**Comment by aimalz** [comment]
I'm closing this issue because this was taken care of last summer.
