### ISSUE TITLE
show that in the permissable "stacking the posteriors" case, no information flows

### ISSUE THREAD

**Issue by davidwhogg** [aimalz/chippr#58]
If you stack posteriors, you get just as good an answer if your data contain no information (so you just re-stack the prior over and over) as you do if your data contain lots of information. In fact, from a bootstrap perspective, the former (no information) will give a *better* N(z). Absurd!

**Comment by aimalz** [comment]
This question prompted an [issue](https://github.com/danielgruen/sumzz/issues/11) elsewhere on GitHub.  I sort of answered an orthogonal question of what the information of the stacked estimator is relative to the information of the redshift distribution it aims to approximate and will write it into our [pedagogical paper draft](https://www.overleaf.com/read/xtgdffzvcvsg) soon.  (If you want to edit it, check for the link in an e-mail from me on 5 May.)

**Comment by aimalz** [comment]
I'm closing this issue because it has been addressed elsewhere.
