### ISSUE TITLE
Refactor catalog production

### ISSUE THREAD

**Issue by aimalz** [aimalz/chippr#61]
The final test case in #25, that of catastrophic outliers as seen in empirical p(z) methods, suggests a different approach that's very similar to how [the previous version](https://github.com/aimalz/prob-z/tree/master/nz) was at the very end.

All the test cases currently implemented in #25 begin with true redshifts, devise p(z_est | z_true, params), and use that to get p(z_true | z_est, params).  What I should really be doing is devising a probability distribution in the space of p(z_true, z_est | params, n_true(z)), sampling pairs (z_true, z_est), and evaluating p(z_true | z_est, params) as the horizontal cuts through the z_true, z_est plot.

Here are some sketchy notes to remind me of how I want this to work, accounting for how the true n(z) and interim prior must enter into catalog construction in this way:
![20170627_131138](https://user-images.githubusercontent.com/8606810/27615471-4c7a0416-5b5d-11e7-9648-c0b89fb47b5a.jpg)

**Comment by drphilmarshall** [comment]
A crucial note: this approach will need to be verified against the
validation cases you have already implemented using the simpler symmetric
conditional distributions.

Might be worth writing out the math in latex as well, for inspection. I'd
use an appendix for now, I think - you can always simplify and promote it
later.

**Comment by aimalz** [comment]
Re: verification, absolutely!

I also wrote up what I'm doing in the [paper](https://github.com/aimalz/chippr/blob/issue/61/refactor_catalog/research/paper/draft.pdf).

**Comment by aimalz** [comment]
Sorry I forgot to update this issue!  The verification step was a success, and the new figures should now appear in the draft linked to in the previous comment.
