### ISSUE TITLE
Replace basic probability distribution construction

### ISSUE THREAD

**Issue by aimalz** [aimalz/chippr#68]
The whole `mvn.py`/`multi_dist.py`/`gmix.py`/`gauss.py`/`discrete.py` system is woefully inefficient.  This issue can be closed when this redundant structure is eliminated in favor of something based on [`scipy.stats`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html) and/or [`qp`](https://github.com/aimalz/qp) and/or [`pomegranate`](https://github.com/jmschrei/pomegranate) objects that are much faster.

**Comment by aimalz** [comment]
This has been resolved in [branch 68](https://github.com/aimalz/chippr/tree/issue/68/restructure_probs) and merged into [branch 67](https://github.com/aimalz/chippr/tree/issue/67/reboot_fiducial) for further integration into the scripts.

**Comment by aimalz** [comment]
FYI, that simple change cut runtime of the mock data simulation by a factor of over 10,000!

**Comment by drphilmarshall** [comment]
Egad. Good catch. Just to check what you mean by mock data simulation: does
that mean your likelihood function evaluations have also sped up by a
factor of 10^4?

**Comment by aimalz** [comment]
No, the changes are only in the catalog generation and are totally separate from the hierarchical inference.  The inference uses simple array operations that only work because I baked in the piecewise constant format.  I could potentially speed them up with Cython instead of numpy, but if I propagate the changes that sped up the simulation code through to the inference code, there'd also be a way to accommodate different formats for n(z).  I'm not sure if it's possible for pomegranate's mixture of uniform distributions to be faster than array operations alone, even in numpy instead of Cython, but I can check somewhere down the line after I put out some fires for paper 0.
